// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecCommandReq {
    #[prost(message, optional, tag = "1")]
    pub command: ::core::option::Option<Command>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecCommandResp {
    #[prost(message, optional, tag = "1")]
    pub command_resp: ::core::option::Option<CommandResp>,
}
/// commands //////////////////////////
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(oneof = "command::Command", tags = "1, 2, 3, 4, 5")]
    pub command: ::core::option::Option<command::Command>,
}
/// Nested message and enum types in `Command`.
pub mod command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        AddQueue(super::AddQueue),
        #[prost(message, tag = "2")]
        AddEvent(super::AddEvent),
        #[prost(message, tag = "3")]
        AddEvents(super::AddEvents),
        #[prost(message, tag = "4")]
        UpdateEventStatus(super::UpdateEventStatus),
        #[prost(message, tag = "5")]
        CreateTransaction(super::CreateTransaction),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddQueue {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddEvent {
    #[prost(string, tag = "1")]
    pub queue_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub event: ::core::option::Option<Event>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddEvents {
    #[prost(string, tag = "1")]
    pub queue_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateEventStatus {
    #[prost(string, tag = "1")]
    pub queue_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub event_id: u64,
    #[prost(message, optional, tag = "3")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTransaction {
    #[prost(string, tag = "1")]
    pub queue_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub event_id: u64,
}
/// command responses /////////////////
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandResp {
    #[prost(oneof = "command_resp::CommandResp", tags = "1, 2, 3, 4, 5, 6")]
    pub command_resp: ::core::option::Option<command_resp::CommandResp>,
}
/// Nested message and enum types in `CommandResp`.
pub mod command_resp {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum CommandResp {
        #[prost(message, tag = "1")]
        AddQueueResp(super::AddQueueResp),
        #[prost(message, tag = "2")]
        AddEventResp(super::AddEventResp),
        #[prost(message, tag = "3")]
        AddEventsResp(super::AddEventsResp),
        #[prost(message, tag = "4")]
        UpdateEventStatusResp(super::UpdateEventStatusResp),
        #[prost(message, tag = "5")]
        CreateTransactionResp(super::CreateTransactionResp),
        #[prost(message, tag = "6")]
        ErrorResp(super::ErrorResp),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AddQueueResp {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AddEventResp {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddEventsResp {
    #[prost(uint64, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateEventStatusResp {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateTransactionResp {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorResp {
    #[prost(string, tag = "1")]
    pub error_msg: ::prost::alloc::string::String,
}
/// shared entities //////////////////
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub attributes: ::prost::alloc::vec::Vec<Attribute>,
    #[prost(message, optional, tag = "4")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attribute {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Status {
    #[prost(oneof = "status::DataType", tags = "1, 2, 3, 4, 5, 6")]
    pub data_type: ::core::option::Option<status::DataType>,
}
/// Nested message and enum types in `Status`.
pub mod status {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum DataType {
        #[prost(message, tag = "1")]
        Queued(super::Queued),
        #[prost(message, tag = "2")]
        Running(super::Running),
        #[prost(message, tag = "3")]
        Complete(super::Complete),
        #[prost(message, tag = "4")]
        Errored(super::Errored),
        #[prost(message, tag = "5")]
        MissedHeartbeat(super::MissedHeartbeat),
        #[prost(message, tag = "6")]
        Timedout(super::Timedout),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Queued {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Running {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Complete {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Errored {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MissedHeartbeat {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Timedout {}
/// Generated client implementations.
pub mod exchange_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ExchangeClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ExchangeClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ExchangeClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ExchangeClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ExchangeClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn exec_command(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecCommandReq>,
        ) -> std::result::Result<
            tonic::Response<super::ExecCommandResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/exchange.Exchange/ExecCommand",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("exchange.Exchange", "ExecCommand"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod exchange_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ExchangeServer.
    #[async_trait]
    pub trait Exchange: std::marker::Send + std::marker::Sync + 'static {
        async fn exec_command(
            &self,
            request: tonic::Request<super::ExecCommandReq>,
        ) -> std::result::Result<tonic::Response<super::ExecCommandResp>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct ExchangeServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ExchangeServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ExchangeServer<T>
    where
        T: Exchange,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/exchange.Exchange/ExecCommand" => {
                    #[allow(non_camel_case_types)]
                    struct ExecCommandSvc<T: Exchange>(pub Arc<T>);
                    impl<T: Exchange> tonic::server::UnaryService<super::ExecCommandReq>
                    for ExecCommandSvc<T> {
                        type Response = super::ExecCommandResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecCommandReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Exchange>::exec_command(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecCommandSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ExchangeServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "exchange.Exchange";
    impl<T> tonic::server::NamedService for ExchangeServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
